name: signature
description: A Flutter plugin providing performance optimized signature canvas with ability to set custom style, boundaries and initial state.
version: 5.4.0
homepage: https://github.com/4Q-s-r-o/signature

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.0+1
  image:
    git:
      url: https://github.com/brendan-duncan/image.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
